config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  devise_for :users
  root to: 'messages#index'
  resources :messages do
    resources :orders, only: [:index, :create]
  end
  resources :chats, only: [:index, :create, :show]
  resources :users, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :message
  belongs_to :user
  has_one :order
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_one :order
  has_one :history


  with_options presence: true do
    validates :name
    validates :image
    validates :description
        with_options inclusion: { in: (100..500)} do
          with_options format: { with: /\A[0-9]+\z/} do
            validates :price
          end
        end

   end
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :history
end

app/models/order_history.rb
class OrderHistory
  include ActiveModel::Model
  attr_accessor :name, :user_id, :message_id, :token

  with_options presence: true do
    validates :name
    validates :token
    validates :user_id
    validates :message_id
  end


  def save
    history = History.create(user_id: user_id, message_id: message_id)
    Order.create(name: name, history_id: history.message_id)  
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         with_options presence: true do
          validates :nickname
          validates :email, uniqueness: true
          validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
      
          with_options format: { with: /\A[ぁ-んァ-ン一-龥々]+\z/ } do
            validates :last_name
            validates :first_name
            validates :parent_name
          end
          with_options format: { with: /\A[ァ-ヶー－]+\z/ } do
            validates :last_name_kana
            validates :first_name_kana
          end
        end

        has_many :messages
        has_many :user_rooms
        has_many :chats
        has_many :rooms, through: :user_rooms
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :last_name, :first_name, :last_name_kana,
                                                       :first_name_kana, :parent_name])
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @my_chats=current_user.chats
    @chat_partners=User.where.not(id:current_user.id)#自分以外
  end

  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    if user_rooms.nil? #上記で取得できなかった場合の処理
      #新しいroomを作成して保存
      @room = Room.new
      @room.save
      #@room.idと@user.idをUserRoomのカラムに保存(１レコード)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
      #@room.idとcurrent_user.idをUserRoomのカラムに保存(１レコード)
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
    else
      #取得している場合は、user_roomsに紐づいているroomテーブルのレコードを@roomに代入
      @room = user_rooms.room
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
  end

  private
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :find_params, only:[:show, :edit, :update, :destroy ]
  before_action :redirect_root, only:[:edit, :update, :destroy]

  
  def index
    @messages = Message.all.order(created_at: "DESC")
    @user = current_user
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @message.update(message_params)
      redirect_to message_path,method: :patch  
   else
     render :edit
   end
  end

  def destroy
    
    @message.destroy
    redirect_to root_path
  end


  private
  def message_params
    params.require(:message).permit(:name, :image, :description, :price).merge(user_id: current_user.id)
  end

  def find_params
    @message = Message.find(params[:id])
  end

  def redirect_root
    redirect_to root_path unless current_user.id == @message.user_id
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_params, only: [:index, :create]
  before_action :redirect_root, only:[:index]



  def index
    @order_history = OrderHistory.new
   
  end


  def create
    @order_history = OrderHistory.new(order_params)
    if @order_history.valid?
      pay_item
      @order_history.save
      redirect_to root_path
    else
      render action: :index
    end
  end
  
  private
 def order_params
  params.require(:order_history).permit(:name).merge(user_id: current_user.id, token: params[:token], message_id:params[:message_id])
 end

 def find_params
  @message = Message.find(params[:message_id])
end
def redirect_root
  redirect_to root_path if current_user.id == @message.user_id
end

def pay_item
  Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      Payjp::Charge.create(
        amount: @message.price,
        card: order_params[:token],
        currency: 'jpy' 
      )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/create.js.erb
$('.message').append("<p style='text-align: left;'><%= @chat.message %></p>");
$('input[type=text]').val("")

app/views/chats/index.html.erb
<%= render "shared/header" %>
<table class="rooms">
  <tbody>
    <tr>
      <td>
        <%@chat_partners.each do |chat_partner|%>
          <%=link_to "#{chat_partner.nickname}さんとのトークルーム","/chats/#{chat_partner.id}"%><br>
        <%end%>
      </td>
    </tr>
  </tbody>
</table>
<%= render "shared/footer" %>

app/views/chats/show.html.erb
<%= render "shared/header" %>
<div class="container">
    <div class="row">
        <div class="col-xs-6">
        <div class="partner" >
            <h2 id="room" data-room="<%= @room.id %>" data-user="<%= current_user.id %>"><%= @user.nickname %> さんとのチャット</h2>
                  </div>

      <div class="chats">
            <table class="message table">
            <thead>
                <tr>
                  <th style="text-align: left; font-size: 20px;"><%= current_user.nickname %></th>
                  <th style="text-align: right; font-size: 20px;"><%= @user.nickname %></th>
                </tr>
              </thead>
              
    
              <% @chats.each do |chat| %>
                <% if chat.user_id == current_user.id %>
                <tbody>
                  <tr>
                    <th>
                    <div class="says">
                      <p style="text-align: left;"><%= chat.message %></p>
                    </div>
                    </th>
                    <th></th>
                  </tr>
                </tbody>
                <% else %>
                <tbody>
                  <tr>
                    <th></th>
                    <th>
                    <div class="says">
                      <p style="text-align: right;"><%= chat.message %></p>
                    </div>
                    </th>
                  </tr>
                </tbody>
                <% end %>
              <% end %>

            </table>
              </div>
            <div class="send">           
            <%= form_with model: @chat do |f| %>
              <%= f.text_field :message %>
              <%= f.hidden_field :room_id %>
              <%= f.submit "投稿する" ,class:"send" %>
            <% end %>
            </div>
        </div>
    </div>
</div>
<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiaryApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
    <%= stylesheet_link_tag 'application', media: 'all'  %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('logo_transparent.png' , size: '185x185'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">写真情報を入力</h2>
    <%= form_with model: @message, local: true do |f| %>

  
    <%= render 'shared/error_messages', model: f.object %>
    
    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        投稿画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        投稿名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          写真の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>


    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥100~500)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）100" %>
        </div>
        
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている写真、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        暴行・差別とみなされる写真の投稿はご遠慮ください
      <p class="sentence">
        また、投稿をもちまして
        <a href="#">写真投稿規約およびガイドライン</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">DiaryApp利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('linkedin_banner_image_2.png' , size: '400x200'), "/" %>
    <p class="inc">
      ©︎DiaryApp,Inc.
    </p>
  </footer>
</div>

app/views/messages/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      かんたん保育日報アプリ
    </h2>
    <p class='service-explain'>
      個人別に相談もできる
    </p>
    <p class='service-explain'>
      お子様の成長をもっと近くで見ることが出来ます
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面上部の「人生を変えるフリマアプリ」帯部分  %>

  
  <div class='feature-contents'>
    <h2 class='title'>
      DiaryAppの特徴
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "music_gassyou_kids_world.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          簡単にお子様の活動を見ることができる
        </h3>
        <p class='feature-list-description'>
          ノートでスタッフとやり取りする手間が省ける
        </p>
      </li>
      <li class='list'>
        <%= image_tag "soudan_setsumei_business_woman.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          個別にスタッフと相談することも出来ます
        </h3>
        <p class='feature-list-description'>
          チャットルームを作成して相談可能もちろん秘密は遵守します
        </p>
      </li>
      <li class='list'>
        <%= image_tag "youchien_tsuuen_bag.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          当日の出席も<br>簡単に報告
        </h3>
        <p class='feature-list-description'>
          わざわざ電話しなくてもOKです
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAの特徴 %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>園児の写真</h2>
    <%= link_to '新規投稿', "#", class: "subtitle" %>
    <ul class='item-lists'>

      <%# 商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <% @messages.each do |message| %>
      <li class='list'>
        <%= link_to message_path(message.id), method: :get do %>
        <div class='item-img-content'>
          <%= image_tag message.image.variant(resize: '500x500'), class: "item-img" %>

        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= message.name %>
          </h3>
          <div class='item-price'>
            <span><%= message.price %>円</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>    
        <% end %>    
      </li>
     <% end %>

      <%# //商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>

      <%# 商品がない場合は以下のダミー商品が表示されるようにしましょう %>
      <%# 商品がある場合は表示されないようにしましょう %>
    
      <%# //商品がある場合は表示されないようにしましょう %>
      <%# //商品がない場合は以下のダミー商品が表示されるようにしましょう %>
      <% if @messages.length == 0 %>
      <li class='list'>
        <%= link_to '#' do %>
        <%= image_tag "youtube_profile_image.png", class: "item-img" %>
        <div class='item-info'>
          <h3 class='item-name'>
            写真を投稿してね！
          </h3>
          <div class='item-price'>
            <span>100円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
       <% end %>
    </ul>
  </div>
  <%# /商品一覧 %>
</div>
<%= link_to(new_message_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>投稿する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/messages/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('logo_transparent.png' , size: '185x185'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">写真情報を入力</h2>
    <%= form_with model: @message, local: true do |f| %>

  
    <%= render 'shared/error_messages', model: f.object %>
    
    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        投稿画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        投稿名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          写真の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>


    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥100~500)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）100" %>
        </div>
        
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている写真、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        暴行・差別とみなされる写真の投稿はご遠慮ください
      <p class="sentence">
        また、投稿をもちまして
        <a href="#">写真投稿規約およびガイドライン</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">DiaryApp利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('linkedin_banner_image_2.png' , size: '400x200'), "/" %>
    <p class="inc">
      ©︎DiaryApp,Inc.
    </p>
  </footer>
</div>

app/views/messages/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @message.name %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @message.image ,class:"item-box-img" %>

     
    </div>
    <div class="item-price-box">
      <span class="item-price">
        <%= @message.price %>円
      </span>
     
    </div>
  <% if user_signed_in? %>
    <% if current_user.id == @message.user_id %>
      <%= link_to "投稿の編集", edit_message_path, method: :get, class: "item-red-btn" %>
      <p class="or-text">or</p>
     <%= link_to "削除", message_path(@message.id), method: :delete, class:"item-destroy" %>
    <% else %>
    <%= link_to "購入画面に進む", message_orders_path(@message.id), method: :get,class:"item-red-btn"%>
    <% end %>
 <%end%>
  
 


    <div class="item-explain-box">
      <span><%= @message.description %></span>
    </div>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な投稿の通報</span>
      </div>
    </div>
  </div>
  <%# /商品の概要 %>

  <div class="comment-box">
       
      
  </div>
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の投稿
    </a>
    <a href="#" class="change-item-btn">
      後ろの投稿 ＞
    </a>
  </div>
  
</div>

<%= render "shared/footer" %>

app/views/orders/index.html.erb
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      購入内容の確認
    </h1>
    <%# 購入内容の表示 %>
    <div class='buy-item-info'>
      <%= image_tag @message.image, class: 'buy-item-img' %>
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= @message.name %>
        </h2>
        <div class='buy-item-price'>
          <p class='item-price-text'>¥<%= @message.price %></p>
         
        </div>
      </div>
    </div>
    <%# /購入内容の表示 %>

    <%# 支払額の表示 %>
    <div class='item-payment'>
      <h1 class='item-payment-title'>
        支払金額
      </h1>
      <p class='item-payment-price'>
        ¥<%= @message.price %>
      </p>
    </div>
    <%# /支払額の表示 %>

    <%= form_with(model: @order_history, url: message_orders_path, id: 'charge-form', class: 'transaction-form-wrap',local: true) do |f| %>
     <%= render 'shared/error_messages', model: @order_history %>
    <%# カード情報の入力 %>
    <div class='credit-card-form'>
      <h1 class='info-input-haedline'>
        クレジットカード情報入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">カード情報</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :number, class:"input-default", id:"card-number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
        <div class='available-card'>
          <%= image_tag 'card-visa.gif', class: 'card-logo'%>
          <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
          <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
          <%= image_tag 'card-amex.gif', class: 'card-logo'%>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">有効期限</label>
          <span class="indispensable">必須</span>
        </div>
        <div class='input-expiration-date-wrap'>
          <%= f.text_area :exp_month, class:"input-expiration-date", id:"card-exp-month", placeholder:"例)3" %>
          <p>月</p>
          <%= f.text_area :exp_year, class:"input-expiration-date", id:"card-exp-year", placeholder:"例)23" %>
          <p>年</p>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">セキュリティコード</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :cvc, class:"input-default", id:"card-cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
      </div>
    </div>
    <%# /カード情報の入力 %>
    
    <%# 配送先の入力 %>
    <div class='shipping-address-form'>
      <h1 class='info-input-haedline'>
        購入者入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">購入する人の名前を書いてください</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :name, class:"input-default", id:"postal-code", placeholder:"山田太郎", maxlength:"8" %>
      </div>
    </div>
    <%# /配送先の入力 %>
    <div class='buy-btn'>
      <%= f.submit "購入" ,class:"buy-red-btn" %>
    </div>
    <% end %>
  </div>
</div>
<%= render "shared/second-footer"%>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("logo_transparent.png", class:"furima-icon"), "/" %>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to '相談チャット', chats_path , method: :get, class: "category-list" %></li>
      <li><%= link_to '欠席報告', "https://docs.google.com/forms/u/0/d/e/1FAIpQLScgHExyRsd1BRJ0t8w7ZrnLM_ArClhmBTMmGONBaXMnJBZ3Uw/formResponse", class: "brand-list" %></li>
    </ul>
    <ul class='lists-right'>
       <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end%>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>FURIMA利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "logo_transparent.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("linkedin_banner_image_1.png", class:"second-logo"), "/" %>
</header>